# Development
# version: "3"

# services:
#   nginx:
#     image: nginx:stable-alpine
#     ports:
#       - 9000:80   # Use in development
#     volumes:
#       - ./website:/usr/share/nginx/html


# Production
version: '3'

services:
  nginx:
    image: wetagustin/vps-homepage:1.0.1
    container_name: homepage
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/agustinwet.online:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf:ro